var artistas = [
  {
    nombre: "Abraham SP",
    titulo: "Su obra",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
    link: "https://www.youtube.com/watch?v=zzcagc96LLQ&list=RDMMzzcagc96LLQ&start_radio=1"
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Viking Eggeling",
    titulo: "Diagonal Symphony",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
    link: "./assets/videos/1921VikingEggelingDiagonalSymphony.mp4",
    descripcion: "hola",
  },
];
