var artistas = [
  {
    nombre: "Abraham SP",
    titulo: "Su obra",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Digital",
    fecha: "Mayo 2020",
    duracion: "20'",
    tipo: "mp4",
  },
  {
    nombre: "Solimán López",
    titulo: "Pulsar",
    fecha: "Marzo 2020",
    duracion: "10'",
    tipo: "mp4",
  },
];
